### ISSUE TITLE
Allow specifying hash for files to be downloaded.

### ISSUE THREAD

**Issue by deedubs** [yonkornilov/snowcapper#28]
Accepting a src_hash will allow the user to ensure the file is as intended and hasn't been tampered with / changed.

Prior art https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.append and its `source_hash` attribute.  It's a neat trick that it automatically determines the hash type from the length

```
Type    Length
======  ======
sha512     128
sha384      96
sha256      64
sha224      56
sha1        40
md5         32
```

**Comment by yonkornilov** [comment]
Agreed, this is a necessary feature
