### ISSUE TITLE
These can be compressed to a single case statement

### ISSUE THREAD

**Issue by deedubs** [yonkornilov/snowcapper#5]
https://github.com/yonkornilov/snowcapper/blob/e6f70e78beec69ed31ddd805bc99c3245015d513/extract/extract.go#L60

**Comment by yonkornilov** [comment]
#7 was merged:

https://github.com/yonkornilov/snowcapper/blob/3afa771cd87c2a2df3fca8047c580034d10c6b00/extract/extract.go#L74

https://github.com/yonkornilov/snowcapper/blob/3afa771cd87c2a2df3fca8047c580034d10c6b00/extract/extract.go#L107-L123

This also include tests https://github.com/yonkornilov/snowcapper/blob/master/extract/extract_test.go#L9-L133
